### ISSUE TITLE
Can't search for hashtags

### ISSUE THREAD

**Issue by stefanw** [hhromic/python-twitter-toolbox#2]
[This line](https://github.com/hhromic/python-twitter-toolbox/blob/99d17541921c9798f36cb3c72ed76a171fda6927/twtoolbox/cli.py#L39) makes it impossible to search for hashtags because they start with a #.

**Comment by hhromic** [comment]
Hello,
first of all sorry for the way long delay checking this :(.  Good catch!. I fixed the code now to use double hashes (`##`) instead of single to put comments in those files. The idea originally was that you can add own comments inside lists of hashtags and terms for you. Example:

```
## these are the hashtags for listening to politics
#trump
#obama
#whitehouse

## the following are users also for politics
@trump
@obama
```

Thanks again!
